# Generated by Django 3.2.6 on 2021-08-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdatas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='uid',
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
