# Generated by Django 3.2.6 on 2021-08-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdatas', '0002_auto_20210804_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='uid',
            field=models.TextField(default='dummydatas', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
